sudo: false
language: node_js
node_js:
  - '8'
branches:
  only:
  - master
deploy:
  provider: npm
  email: mitmaro_dev_travis_ci_2fa_test@mitmaro.ca
  on:
    repo: MitMaro/travis-ci-npm-2fa-deploy-test
  api_key:
    secure: PC6d4A+CMy2Qob/3Wl9XI6QAWDyRAxM/h/ubK9M8LbEGA4P8LkOctYFfhLBZaLmLVKFKkAabedEaXJWF1b7iPcDmqGBO5IvGBGsWidkqr3s8GjeC7W6B8fOqwyXfuaSFFH+hpo4R6rRKKah5HvB5E+3SAGq1JRIdC73gL5Zg01TUTwz+3l8gHnkRdUlXskdHBZmKk5JLinm2FvFhFVqCOnyt99cgv0hortWveMoRtPvlZ4QRnrX4Is0rDIe0cndxtW5AQ3EQqM2gZWhGejvty+YoD01PMQjOvry8zuDqC+mLkXkPhe+kAjm0chTvW+3/OO63nbz+KY+8AcnQ6QByu8yPFEqzEpAT49Q859QEFBGeznRjUBLldsiuzD+3q5UOIC4XXOxFhr+0OG6Lw7GAUwLdMFjJj3sflJIAb+f/kvcaQ6pa0pvVdleZd6XtdJYMYHhDMyNbrI2ONy4G2i+r4O+b4CclEw2JeEGXwOnmfQlQvc6m5j0kNfXW5xTXkaeYVtSRC+gpNmO5iwi0FMHSj/OmiP3VCTUSABmhpNwWEsfwfSLxBOte0qrnUIP3OyEmTn5aKJe5Ly6VlkuxAxrJUSha9kJ8mPvANuU9yCPAz27opS1lZNfBWkaaLWGsEF+KQZqs29gGVZjjcYZQ+KL9gAJpJ4hsIc/Ixj8BUBQ6ZCI=
