sudo: false
language: node_js
node_js:
  - '8'
branches:
  only:
  - master
deploy:
  provider: npm
  email: mitmaro_dev_travis_ci_2fa_test@mitmaro.ca
  on:
    repo: MitMaro/travis-ci-npm-2fa-deploy-test
  api_key:
    secure: KEl0HynoNmKsi6Ez896ybBKVxMeFv3NJCzWha4t66e3Yzpr0ESFI4zlJIJry5p91qaRH7oRvv6yJPHYC4M5FZqRQp6470Txqj/l8Z6y6+attAodZeXnnfLP+eR7kphfoneYZcE6L4O/vqGbGD6Mm7oB4ApPx4uzQjO+pqbU1TmvEUg34+2310EGSUuqbFORBEzvdlM33E/GBa8rFv190yO+KzznW8yrKHRkgaHiegigAW5Rgzfs/n6Q5UBKB60Cf9QVpv+sYkSRXjjj+CepRmTryexHIdJWehhUqQCKLymJZjOLqXsDS7/F+SrkYQD8rJX3V7VzOVDOr9wbxlW3Px3aZNsmwu5YdK9ZiVM/7MmbZBelkhpftz7mDn+kAW2Boyp+EYt7k4ISPWV6q2OUzN+bCugepQgaRh6rlbkvkz6Pdp8e/qWW7WHWYR3AENoBoMtC99wHFlVfBECrLm+7Sbg6vwi8RppqtMnp7HSMIfXtmYz4mrhO4pQN8p0miYOLSvDX6DPCCoHynx0XE6SF933y92iB/4eSkEu2rUO1XKkYiLtI2+8SHVI182Cg8vvnTL+xjyqwMc9lTMOdmEycbvRh1Cj7bzKmdOJzqNOKWfS1ofiseRu1t2NG50LWW8b2jgbsw5rMdVC1Mzoynh6amXksYXLhHfDUYMvR4h5l/ez0=
